Update the tvOS version from 9.0 to 10.0
This is necessary because the dependency doesn't compile anymore.

Error: Compiling for tvOS 9.0, but module 'FBSnapshotTestCase' has a minimum deployment target of tvOS 10.0